---
- name: Loop a command 5 times
  hosts: localhost 
  tasks:
    - name: Set the run count 
      ansible.builtin.set_fact:
        loop_counter: "{{ count | default(5)}}"
    
    
    - name: debug out 
      ansible.builtin.debug:
        msg: "Count: {{ loop_counter | type_debug }}"

    - name: Run the command repeatedly
      shell: "{{ playbook_dir }}/test_script.py --arg1 Hello --success"
      
      loop: "{{ range(loop_counter|int)|list }}" 
      
